### PR TITLE
Fix/#3 Unexpected Bright Color

### PR DESCRIPTION
**Pull request by kikuchiharuma**
https://github.com/uniba/circuitlab-team/issues/3

### CODE REVIEW

**Review by akisoqls — COMMENTED** [review]
I could not confirm to fix the bug...

image

**Review by akisoqls — COMMENTED** [review]
macOS Safari is OK
スクリーンショット 2024-08-01 18 04 48

**Comment by kikuchiharuma** [comment]
The problem is identified!

An object (to be projected the iframe) has a matrix with negative x-axis, and it may cause interpretation as reversed surface by renderer. 
This seems to be what happen in iOS and Windows.
https://github.com/uniba/circuitlab-team/pull/5/commits/a5498ef8234638e633e5bd3be773fff408ce77ed

IMG_97C52C19A259-1

**Comment by kikuchiharuma** [comment]
Matrix is fine now, but it's still unknown why large value for transparency works.
Setiing to 1.0 causes dark result, so I keep it.

**Review by akisoqls — APPROVED** [review]
I confirmed the bug is removed.

**Pull request merged**
